version: '2.4'

services:
  chromadb:  # Servicio separado para ChromaDB
    build: ./src/backend
    command: python run_chroma.py --port 8001
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/data
    environment:
      - CHROMA_DB_PATH=/data/chroma

  backend:  # Solo para FastAPI
    build: ./src/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - chromadb

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend

volumes:
  chroma_data: