version: '2.4'

services:
  chromadb:
    build: ./src/backend
    command: python run_chroma.py --port 8001  
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/data
      - ./src/backend:/app  
    environment:
      - CHROMA_DB_PATH=/data/chroma
    restart: on-failure

  backend:
    build: ./src/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - chromadb
    restart: unless-stopped

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  chroma_data: