version: '2.4'  # Versión máxima soportada por tu sistema

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma_data

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    depends_on:
      - chromadb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  chroma_data: