version: '3.8'

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma_data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1"]  # Endpoint real de ChromaDB
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s  # Tiempo de espera inicial antes de empezar a verificar
    networks:
      - rag-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      chromadb:
        condition: service_healthy  # Espera a que ChromaDB pase el healthcheck
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
    networks:
      - rag-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rag-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  chroma_data:

networks:
  rag-network:
    driver: bridge